### ISSUE TITLE
Share calendar data between components

### ISSUE THREAD

**Issue by ecumene** [Prmatterson/budget#12]
In *App.jsx* create the state and pass it down:

```js
  const [calendarData, setCalendarData] = useState([]);
  return (
    <div className="grid grid-cols-2">
      <Form setCalendarData={setCalendarData} />
      <Calendar calendarData={calendarData} />
    </div>
  );
```

In *Calendar.jsx*:
```js
export default function Calendar({ calendarData }) {
```

In *Form.jsx*:
```js
setCalendarData((prev) => [...prev, { amount, plusMinus }]);
```

**Comment by Prmatterson** [comment]
completed

**Comment by Prmatterson** [comment]
Super pumped.  Got a warning for "Cannot update a component while rendering a different component warning," searched and found a solution.  Tested it and it works (not sure if it's the ideal fix of course)!  Had to wrap the 'setCalendarData(prev)' line of code with 'useForm' as per the below.

``
export default function Form({ setCalendarData } ) {
  const { register, handleSubmit} = useForm();
  const onSubmit = data => console.log(data);
  useForm(() => {
  setCalendarData((prev) => [...prev, {amount, plusMinus, account, biller, frequency, startDate, endDate}]);
}, []);
``
