### ISSUE TITLE
Create a calendar component 

### ISSUE THREAD

**Issue by ecumene** [Prmatterson/budget#3]
## Calendar component: 

![image](https://user-images.githubusercontent.com/6249465/196061384-16771619-a2f8-4324-8b13-c7c414fc347f.png)

- [x] Create `src/components`
- [x] Make a new component `src/components/Calendar.jsx`
- [x] Calendar will return some HTML that renders a calendar

### Usage:
```jsx
import React from 'react';

export default function Calendar() {
    return (
        // ...
    );
}
```

### Usage:
```jsx
import React from 'react';
import Calendar from './src/components/Calendar';

export default function App() {
    return (
        <Calendar />
    );
}
```

### [Try following this link](https://us-central1-dispatcher-707d6.cloudfunctions.net/dispatcher)

**Comment by Prmatterson** [comment]
having trouble getting the rendering of the page to work.  can't tell what I'm missing as I can't get the potential solutions I'm finding online to work.  also, the "try following this link" just goes to my other project.  I've pushed the latest code to GitHub.  If you can give me any advice on getting the rendering of the page to work I would appreciate it.

**Comment by Prmatterson** [comment]
It's weird as I haven't seen any issues no matter how many times I look, but I can't get any information from anything but the index.html itself to show when i test load the page. It's like the info isn't making it to the div id=root or something isn't exporting or importing.

**Comment by ecumene** [comment]
Hmm. When you do a `npm run dev` you don't get this?

<img width="235" alt="Screen Shot 2022-10-21 at 12 11 02 PM" src="https://user-images.githubusercontent.com/6249465/197222760-e42d7ad5-e587-4706-94b2-c75dd53952db.png">
![Screen Shot 2022-10-21 at 12 11 15 PM](https://user-images.githubusercontent.com/6249465/197222793-4b1b783a-8596-4326-bf1c-3d6bff3fcd13.png)

**Comment by Prmatterson** [comment]
Ah!  I've been using the built in "Go Live" in VSCode (old habit). Based on your result i suppose that doesn't load the other pages.  Good to know! I'll get more of the calendar set up tonight and Saturday.  Thanks again.
