### ISSUE TITLE
Create a shape for schedule

### ISSUE THREAD

**Issue by ecumene** [Prmatterson/budget#5]
Write down in here:

 - What days you need things to happen on 
 - What holdays
 - Monthly, weekly, so on...?

![image](https://user-images.githubusercontent.com/6249465/197403550-75b9eb37-920a-420c-832b-6023e5369201.png)

**Comment by Prmatterson** [comment]
- Amount
    - Income/Expense or +/- (toggle option beside Amount field)
- Account Name
- Single or Repeated Transaction (button option that shows appropriate options automatically)
    - If Single, Specific Date
    - If Repeated,    
        - Based on Date or Day         
            - Specific date of month (e.g. the 1st) and Frequency (e.g. yearly, biweekly) OR
            - Specific day of month (e.g. Monday) and Frequency
        - Holiday exceptions
            - Holidays not relevant, transaction goes ahead on scheduled day
            - Holidays are relevant,
                - Transaction goes ahead on next business day
                - Transaction goes ahead on business day prior to holiday
Description
